#!/bin/sh
#
# vencd: This starts and stops venc.
#
# chkconfig: 2345 32 22
# description: venc
#
# processname: /usr/sbin/venc
# config: /etc/conf.d/venc_conf.xml
# pidfile: /var/run/venc.pid

# automatically export variables to the environment
set -a

PATH=/sbin:/bin:/usr/bin:/usr/sbin

# Source function library.
. /etc/init.d/functions

# Get config.

#RETVAL=0

prog="venc"
binpath="/usr/sbin/venc"
pidfile="/var/run/venc.3.pid"
configfile="/etc/conf.d/c3/venc_conf.xml"
fifopath="/tmp/venc/c3/command.fifo"
args="-m 3 -D -c $configfile -f $fifopath -p $pidfile"

[ -f $binpath ] || exit

start(){
    echo -n "Starting $prog ... "
    start-stop-daemon --start --pidfile $pidfile --exec $binpath -- $args
    sleep 1
    echo "."
}

#default --stop send signal 15 (SIGTERM)
stop(){
    echo -n "Stopping $prog ... "
    start-stop-daemon --stop --quiet -n $prog --pidfile $pidfile
    sleep 1
#    waittodie $pidfile $binpath
    echo "."
}

reload(){
    echo -n "Reloading $prog ... "
    start-stop-daemon --stop --signal 1 -n $prog --pidfile $pidfile
    echo "."
}

# See how we are called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    reload)
        reload
        ;;
    restart)
        stop
	sleep 1
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit 0
