###############################################
# Generated by Code Generator Version 3.4.0.10 #
###############################################
MODNAME="vma_h4ee"

rmmod vma_h4ee  > /dev/null 2>&1

rm /dev/$MODNAME  > /dev/null 2>&1

insmod vma_h4ee.ko

MAJOR=`cat /proc/devices | grep $MODNAME | sed -e 's/vma_h4ee//' | sed -e 's/ //'`

if test -z $MAJOR; then
	echo "The device specified is not found !"
else
	echo "Let's make a node here for $MODNAME with major number $MAJOR"
	mknod /dev/$MODNAME c $MAJOR 0 > /dev/null 2>&1
fi
