#!/bin/sh

# reconfigure wifi
/davinci/dvr/wifi_up

# reconfigure ether net
ifconfig eth0 up `/davinci/dvr/cfg get network eth_ip`
ifconfig eth0 netmask `/davinci/dvr/cfg get network eth_mask`

sleep 3

route del default
route add default gw `/davinci/dvr/cfg get network gateway`   
