#!/bin/sh

cd /dav

# reconfigure wifi
ifconfig rausb0 down 
/bin/rmmod rt73
/bin/insmod rt73.ko

cd /dav/dvr 

# reconfigure ether net
if [ -f /dav/dvr/eth_ip ]; then
    ifconfig eth0 `cat /dav/dvr/eth_ip`
fi

if [ -f /dav/dvr/eth_mask ]; then
    ifconfig eth0 netmask `cat /dav/dvr/eth_mask`
fi

sleep 3

route del default

for gw in `ls gateway*` ; do 
   route add default gw `cat $gw`   
done

