#!/bin/sh
# /etc/init.d/synctime: sync system time to RTC
# chkconfig: 2345 03 71

PATH=/sbin:/bin:/usr/bin

RETVAL=0

prog="fwnetwrok"


start(){
	echo -n "Starting $prog: "
	echo "."
	total_stream_num=`cat /etc/conf.d/c0/venc_conf.xml  |  grep total_num | awk -F'<' '{ print $2 }' |  awk -F'>' '{ print $2 }'`
	/usr/sbin/mount_as_tmpfs  /usr/share/www/cgi-bin/admin/
	if [ -f /usr/share/www/cgi-bin/admin/audiovideo/audiovideo.$total_stream_num.lua ];then
	  cp -f /usr/share/www/cgi-bin/admin/audiovideo/audiovideo.$total_stream_num.lua  /usr/share/www/cgi-bin/admin/audiovideo.lua
	else
	  echo "The /usr/share/www/cgi-bin/admin/audiovideo/audiovideo.$total_stream_num.lua does not exist!! So use the original one"
	  umount /usr/share/www/cgi-bin/admin/
	fi
}

stop(){
    echo -n "Stopping $prog: "
	echo "."
}

# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
    stop
    start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
