
#ifndef __dvrprotocol_h__
#define __dvrprotocol_h__

#include "../cfg.h"

// network service
#define DVRPORT 15111

#define REQDVREX	0x7986a348
#define REQDVRTIME	0x7986a349
#define DVRSVREX	0x95349b63
#define DVRSVRTIME	0x95349b64
#define REQSHUTDOWN	0x5d26f7a3

// dvr net service
struct dvr_req {
    int reqcode;
    int data;
    int reqsize;
};

struct dvr_ans {
    int anscode;
    int data;
    int anssize;
};

enum reqcode_type {
    REQOK =	1,
    REQREALTIME, REQREALTIMEDATA,
    REQCHANNELINFO, REQCHANNELDATA,
    REQSWITCHINFO, REQSHAREINFO,
    REQPLAYBACKINFO, REQPLAYBACK,
    REQSERVERNAME,
    REQAUTH, REQGETSYSTEMSETUP,
    REQSETSYSTEMSETUP, REQGETCHANNELSETUP,
    REQSETCHANNELSETUP, REQKILL,
    REQSETUPLOAD, REQGETFILE, REQPUTFILE,
    REQHOSTNAME, REQRUN,
    REQRENAME, REQDIR, REQFILE,
    REQGETCHANNELSTATE, REQSETTIME, REQGETTIME,
    REQSETLOCALTIME, REQGETLOCALTIME,
    REQSETSYSTEMTIME, REQGETSYSTEMTIME,
    REQSETTIMEZONE, REQGETTIMEZONE,
    REQFILECREATE, REQFILEREAD,
    REQFILEWRITE, REQFILESETPOINTER, REQFILECLOSE,
    REQFILESETEOF, REQFILERENAME, REQFILEDELETE,
    REQDIRFINDFIRST, REQDIRFINDNEXT, REQDIRFINDCLOSE,
    REQFILEGETPOINTER, REQFILEGETSIZE, REQGETVERSION,
    REQPTZ, REQCAPTURE,
    REQKEY, REQCONNECT, REQDISCONNECT,
    REQCHECKID, REQLISTID, REQDELETEID, REQADDID, REQCHPASSWORD,
    REQSHAREPASSWD, REQGETTZIENTRY,
    REQECHO,

    REQ2BEGIN =	200,
    REQSTREAMOPEN, REQSTREAMOPENLIVE, REQSTREAMCLOSE,
    REQSTREAMSEEK, REQSTREAMGETDATA, REQSTREAMTIME,
    REQSTREAMNEXTFRAME, REQSTREAMNEXTKEYFRAME, REQSTREAMPREVKEYFRAME,
    REQSTREAMDAYINFO, REQSTREAMMONTHINFO, REQLOCKINFO, REQUNLOCKFILE, REQSTREAMDAYLIST,
    REQOPENLIVE,
    REQ2ADJTIME,
    REQ2SETLOCALTIME, REQ2GETLOCALTIME, REQ2SETSYSTEMTIME, REQ2GETSYSTEMTIME,
    REQ2GETZONEINFO, REQ2SETTIMEZONE, REQ2GETTIMEZONE,
    REQSETLED,
    REQSETHIKOSD,                                               // Set OSD for hik's cards
    REQ2GETCHSTATE,
    REQ2GETSETUPPAGE,
    REQ2GETSTREAMBYTES,
    REQ2GETSTATISTICS,
    REQ2KEYPAD,
    REQ2PANELLIGHTS,
    REQ2GETJPEG,
    REQ2STREAMGETDATAEX,
    REQ2SYSTEMSETUPEX,
    REQ2GETGPS,

    REQ3BEGIN = 300,
    REQSENDDATA,
    REQGETDATA,
    REQCHECKKEY,
    REQUSBKEYPLUGIN, // plug-in a new usb key. (send by plug-in autorun program)

    // for communicate inside or between eagle boards
    REQ5BEGIN = 500,

    // Screen setup
    REQSCREEENSETMODE,
    REQSCREEENLIVE, REQSCREENPLAY, REQSRCEENINPUT, REQSCREENSTOP, REQSCREENAUDIO,

    REQGETSCREENWIDTH, REQGETSCREENHEIGHT,
    REQDRAWREFRESH, REQDRAWSETAREA,
    REQDRAWSETCOLOR, REQDRAWGETCOLOR,
    REQDRAWSETPIXELMODE, REQDRAWGETPIXELMODE,
    REQDRAWPUTPIXEL, REQDRAWGETPIXEL,
    REQDRAWLINE, REQDRAWRECT,
    REQDRAWFILL, REQDRAWCIRCLE, REQDRAWFILLCIRCLE,
    REQDRAWBITMAP, REQDRAWSTRETCHBITMAP,
    REQDRAWSETFONT, REQDRAWTEXT, REQDRAWTEXTEX,
    REQDRAWREADBITMAP,

    REQMAX
};

enum anscode_type {
    ANSERROR =1, ANSOK,
    ANSREALTIMEHEADER, ANSREALTIMEDATA, ANSREALTIMENODATA,
    ANSCHANNELHEADER, ANSCHANNELDATA,
    ANSSWITCHINFO,
    ANSPLAYBACKHEADER, ANSSYSTEMSETUP, ANSCHANNELSETUP, ANSSERVERNAME,
    ANSGETCHANNELSTATE,
    ANSGETTIME, ANSTIMEZONEINFO, ANSFILEFIND, ANSGETVERSION, ANSFILEDATA,
    ANSKEY, ANSCHECKID, ANSLISTID, ANSSHAREPASSWD, ANSTZENTRY,
    ANSECHO,

    ANS2BEGIN =	200,
    ANSSTREAMOPEN, ANSSTREAMDATA,ANSSTREAMTIME,
    ANSSTREAMDAYINFO, ANSSTREAMMONTHINFO, ANSLOCKINFO, ANSSTREAMDAYLIST,
    ANS2RES1, ANS2RES2, ANS2RES3,                        	// reserved, don't use
    ANS2TIME, ANS2ZONEINFO, ANS2TIMEZONE, ANS2CHSTATE, ANS2SETUPPAGE, ANS2STREAMBYTES,
    ANS2JPEG, ANS2STREAMDATAEX, ANS2SYSTEMSETUPEX, ANS2GETGPS,

    ANS3BEGIN = 300,
    ANSSENDDATA,
    ANSGETDATA,

    // for communicate inside or between eagle boards
    ANS5BEGIN = 500,
    ANSGETSCREENWIDTH, ANSGETSCREENHEIGHT,
    ANSDRAWGETPIXELMODE, ANSDRAWGETCOLOR, ANSDRAWGETPIXEL, ANSDRAWREADBITMAP,

    ANSMAX
};

#ifndef TRUE
#define TRUE (1)
#endif

#ifndef FALSE
#define FALSE (0)
#endif

#ifndef UINT32
#define UINT32 unsigned int
#endif

#endif							// __dvrprotocol_h__
