###############################################
# Generated by Code Generator Version 3.8.0.4 #
###############################################
MODNAME="vma_die"

rmmod vma_die  > /dev/null 2>&1

rm /dev/$MODNAME  > /dev/null 2>&1

insmod vma_die.ko

MAJOR=`cat /proc/devices | grep $MODNAME | sed -e 's/vma_die//' | sed -e 's/ //'`

if test -z $MAJOR; then
	echo "The device specified is not found !"
else
	echo "Let's make a node here for $MODNAME with major number $MAJOR"
	mknod /dev/$MODNAME c $MAJOR 0
fi
