#!/bin/sh
# reconfigure wifi
if [ -f /var/dvr/wifidev ] ; then
  interface=`cat /var/dvr/wifidev`
  if [ -d /sys/class/net/${interface} ] ; then
      /bin/ifconfig ${interface} down
      /sbin/rmmod rt73
  fi
fi
