#!/bin/sh

# reconfigure ether net
ifconfig eth0:1 up `/davinci/dvr/cfg get network eth_ip`
ifconfig eth0:1 netmask `/davinci/dvr/cfg get network eth_mask`

# reconfig wifi, (if interface availabe)
if [ -f /var/dvr/wifidev ] ; then
  interface=`cat /var/dvr/wifidev`
  if [ -d /sys/class/net/${interface} ] ; then 
      /bin/ifconfig ${interface} down 
      /bin/rmmod rt73
      /bin/insmod /davinci/rt73.ko
  fi
fi

sleep 3

route del default
route add default gw `/davinci/dvr/cfg get network gateway`
