#!/bin/sh
#
# httpd: This starts and stops http server.
#
# chkconfig: 2345 18 50
# description: http server (boa)
#
# processname: /usr/sbin/boa
# config: /etc/conf.d/boa.conf
# pidfile: /var/run/boa.pid
set -a

PATH=/sbin:/bin:/usr/bin:/usr/sbin

# Source function library.
. /etc/init.d/functions

prog="boa"
args="-c /usr/share/www -f /etc/conf.d/boa/boa.conf"
binpath="/usr/sbin/boa"
pidfile="/var/run/boa.pid"

[ -f $binpath ] || exit 1

start(){
	echo -n "Starting $prog: "
	start-stop-daemon --start --quiet -n $prog --exec $binpath -- $args
	echo "."
}

stop(){
	echo -n "Stopping $prog: "
	start-stop-daemon --stop --quiet -n $prog --pidfile $pidfile
	waittodie $pidfile $binpath
	echo "."
}

reload(){
	echo -n "Reloading configuration $prog: "	
	start-stop-daemon --stop --signal 1 --quiet -n $prog --pidfile $pidfile
	echo "."
}

# See how we were called.
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload)
		reload
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac

exit 0

