#!/bin/sh

# reconfigure ether net
route del default
ifconfig eth0:1 down
ifconfig eth0:1 `/davinci/dvr/cfg get network eth_ip`
ifconfig eth0:1 netmask `/davinci/dvr/cfg get network eth_mask`
route add default gw `/davinci/dvr/cfg get network gateway`

# reconfig wifi, (if interface availabe)
if [ -f /var/dvr/wifidev ] ; then
  interface=`cat /var/dvr/wifidev`
  if [ -d /sys/class/net/${interface} ] ; then
      /bin/ifconfig ${interface} down
      /bin/rmmod rt73
      /bin/insmod /davinci/rt73.ko
  fi
fi

