#!/bin/sh

# reconfigure ether net
ieth=eth0:1
eth_ip=`/davinci/dvr/cfg get network eth_ip`
eth_mask=`/davinci/dvr/cfg get network eth_ip`

if [ -z "$eth_ip" ] ; then 
  eth_ip=192.168.1.100
  eth_mask=255.255.255.0
fi

ifconfig eth0:1 up $eth_ip 
ifconfig eth0:1 netmask $eth_mask

# reconfig wifi, (if interface availabe)
if [ -f /var/dvr/wifidev ] ; then
  interface=`cat /var/dvr/wifidev`
  if [ -d /sys/class/net/${interface} ] ; then 
      /bin/ifconfig ${interface} down 
      /bin/rmmod rt73
      /bin/insmod /davinci/rt73.ko
  fi
fi

sleep 3

route del default

gateway=`/davinci/dvr/cfg get network gateway`
if [ -n "$gateway" ] ; then
route add default gw $gateway
fi
