#!/bin/sh
# Hot-plug script for Eagle32 project

devpath=/sys$2
devname=${devpath##*/}

devclass=$2
devclass=${devclass#/}
devclass=${devclass%%/*}

subsys=$2
subsys=${subsys#/}
subsys=${subsys#*/}
subsys=${subsys%%/*}

if [ ${devclass} != "block" -a ${devclass} != "class"  ] ; then
   exit
fi

lockfile=/var/dvr/lock_${devclass}_${subsys}_${devname}_$1
if [ -f ${lockfile} ]; then
    exit
fi    

echo 1 > ${lockfile}

#  dvrsvr information?
dvrpidfile=/var/dvr/dvrsvr.pid

#  dvrsvr current working disk.
dvrcurdisk=/var/dvr/dvrcurdisk

# where dvr disks mounted.
dvrmountdir=/var/dvr/disks

if [ ! -d ${dvrmountdir} ] ; then
    mkdir ${dvrmountdir}
fi

# where archive disks mounted.
dvrarchdir=/var/dvr/arch

if [ ! -d ${dvrarchdir} ] ; then
    mkdir ${dvrarchdir}
fi

# hotplug disk mounted here.
xmountdir=/var/dvr/xdisk

if [ -f /var/dvr/TZ ] ; then
  TZ=`cat /var/dvr/TZ`
  export TZ
fi

case $1 in
    "add")

        # hotplug block device (USB disk)
        if [ ${devclass} = "block" -a -r ${devpath}/dev  ] ; then
            devnum=`cat ${devpath}/dev`
            # generate device if not exist
            if [ -e /dev/${devname} ] ; then
                rm /dev/${devname}
            fi
            mknod /dev/${devname} b ${devnum%%:*} ${devnum##*:}

            partition=${devname##*[a-z]}
            if [ ${partition:-0} -ge 1 -a ! -f ${xmountdir}/mount_${devname} ]; then

                echo  ${xmountdir}/${devname} > ${xmountdir}/mount_${devname}
                mkdir -p ${xmountdir}/${devname}

                if mount /dev/${devname} ${xmountdir}/${devname} -t ext3 -o noatime,data=ordered ; then
                    if [ -f ${xmountdir}/${devname}/archive ] ; then
                        d_mount=${dvrarchdir}/d_${devname}
                    else
                        d_mount=${dvrmountdir}/d_${devname}
                    fi

                    if umount ${xmountdir}/${devname} ; then
                        rm -r ${xmountdir}/${devname}
                        mkdir -p ${d_mount}
                        if mount /dev/${devname} ${d_mount} -t ext3 -o noatime,data=ordered ; then
                            # mark mounted disk
                            echo  ${d_mount} > ${xmountdir}/mount_${devname}
                        else
                            rm ${xmountdir}/mount_${devname}
                        fi

                    fi

                elif mount /dev/${devname} ${xmountdir}/${devname} -t ext2 -o noatime ; then
                    if [ -f ${xmountdir}/${devname}/archive ] ; then
                        d_mount=${dvrarchdir}/d_${devname}
                    else
                        d_mount=${dvrmountdir}/d_${devname}
                    fi

                    if umount ${xmountdir}/${devname} ; then
                        rm -r ${xmountdir}/${devname}
                        mkdir -p ${d_mount}
                        if mount /dev/${devname} ${d_mount} -t ext2 -o noatime ; then
                            # mark mounted disk
                            echo  ${d_mount} > ${xmountdir}/mount_${devname}
                        else
                            rm ${xmountdir}/mount_${devname}
                        fi

                    fi

                elif mount /dev/${devname} ${xmountdir}/${devname} -o shortname=winnt ; then

                    # dvr recording disk ?
                    if [ -f ${xmountdir}/${devname}/dvrdisk -o -f ${xmountdir}/${devname}/DVRDISK ] ; then

                        if umount ${xmountdir}/${devname} ; then

                            d_mount=${dvrmountdir}/d_${devname}

                            rm -r ${xmountdir}/${devname}
                            
                            # do dosfs check here
                            /davinci/dosfsck -a /dev/${devname}

                            mkdir -p ${d_mount}
                            if mount /dev/${devname} ${d_mount} -o shortname=winnt ; then
                                rm -f ${d_mount}/FSCK*
                                # mark mounted disk
                                echo  ${d_mount} > ${xmountdir}/mount_${devname}
                            else 
                                rm ${xmountdir}/mount_${devname}
                            fi
                        fi

                    # dvr archive disk ?
                    elif [ -f ${xmountdir}/${devname}/archive -o -f ${xmountdir}/${devname}/ARCHIVE ] ; then

                        if umount ${xmountdir}/${devname} ; then

                            d_mount=${dvrarchdir}/d_${devname}

                            rm -r ${xmountdir}/${devname}
                            
                            # do dosfs check here
                            /davinci/dosfsck -a /dev/${devname}

                            mkdir -p ${d_mount}
                            if mount /dev/${devname} ${d_mount} -o shortname=winnt ; then
                                rm -f ${d_mount}/FSCK*
                                # mark mounted disk
                                echo  ${d_mount} > ${xmountdir}/mount_${devname}
                            else 
                                rm ${xmountdir}/mount_${devname}
                            fi
                        fi
                        
                    # autorun disk .. key ...
                    elif [ -f ${xmountdir}/${devname}/key ] ; then

                        if /davinci/dvr/volumeid /dev/${devname} ${xmountdir}/${devname} ; then
                            # key check passed
                            echo ${xmountdir}/${devname} > ${xmountdir}/mount_${devname}
                            
                            USBROOT=${xmountdir}/${devname} 
                            export USBROOT

                            # check directory 510
                            if [ -d ${USBROOT}/510 ]; then 
                                EXEDIR=${USBROOT}/510
                            else
                                EXEDIR=${USBROOT}
                            fi

                            export EXEDIR
                            cd ${EXEDIR}

                            for autoruncheck in `ls *.check`
                            do
                                if /davinci/dvr/md5check ${autoruncheck} ; then
                                    autorun_file=${autoruncheck%.check}.autorun
                                    if [ -x ${autorun_file} ] ; then
                                        # run autorun file
                                        mkdir /home/usbrun_${autorun_file}
                                        cd /home/usbrun_${autorun_file}
                                        ${EXEDIR}/${autorun_file}  &
                                    fi
                                fi
                            done

                            cd /

                        else    # no autorun file

                            cd /
                            if umount ${xmountdir}/${devname} ; then
                                rm -r ${xmountdir}/${devname}
                                rm ${xmountdir}/mount_${devname}
                            fi
                          
                        fi

                    # autorun disk by usbkey
                    elif [ -f ${xmountdir}/${devname}/usbkey ] ; then

                        # check auto runable disk
                        cd ${xmountdir}/${devname}		# required to be current dir, so usbcheck can read FW file.

                        autorun_appid=`cat /davinci/ID/APPID` 
                        autorun_file_app=`/davinci/dvr/usbcheck /dev/${devname%[1-9]} usbkey ${autorun_appid}`
                        autorun_file=`/davinci/dvr/usbcheck /dev/${devname%[1-9]} usbkey`
                        if [ -f ${xmountdir}/${devname}/${autorun_file} ] ; then

                            echo ${xmountdir}/${devname} > ${xmountdir}/mount_${devname}

                            mkdir /home/usbautorun
                            cd /home/usbautorun
                            # run autorun file
                            EXEDIR=${xmountdir}/${devname}
                            export EXEDIR
                            USBROOT=${EXEDIR}
                            export USBROOT
                            ${EXEDIR}/${autorun_file}  &
                           
                        elif [ -f ${xmountdir}/${devname}/${autorun_file_app} ] ; then

                            echo ${xmountdir}/${devname} > ${xmountdir}/mount_${devname}

                            mkdir /home/usbautorun
                            cd /home/usbautorun
                            # run autorun file
                            EXEDIR=${xmountdir}/${devname}
                            export EXEDIR
                            USBROOT=${EXEDIR}
                            export USBROOT
                            ${EXEDIR}/${autorun_file}  &
                           
                        else    # no autorun file

                            cd /
                            if umount ${xmountdir}/${devname} ; then
                                rm -r ${xmountdir}/${devname}
                            fi
                           
                        fi
                        
                    # other disk
                    else
                        if umount ${xmountdir}/${devname} ; then
                            rm -r ${xmountdir}/${devname}
                        fi
                    fi

                else    # can't mount this disk

                    rm ${xmountdir}/mount_${devname}
                    rm -r ${xmountdir}/${devname}

                fi      # mounted
            fi      # partitions 

        fi	# block device 

        # charactor device
        if [ ${devclass} = "class" -a -r ${devpath}/dev  ] ; then
            devnum=`cat ${devpath}/dev`
            # generate device if not exist
            if [ -e /dev/${devname} ] ; then
                rm /dev/${devname}
            fi
            mknod /dev/${devname} c ${devnum%%:*} ${devnum##*:}
        fi

        # check usb wifi
        if [  ${devclass} = "class" -a ${subsys} = "net" -a -d ${devpath}/wireless ]; then
            echo ${devname} > /var/dvr/wifidev
            /bin/sleep 2

            wifi_essid=`/davinci/dvr/cfg get network wifi_essid`
            wifi_enc=`/davinci/dvr/cfg get network wifi_enc`
            wifi_key=`/davinci/dvr/cfg get network wifi_key`
            wifi_ip=`/davinci/dvr/cfg get network wifi_ip`
            wifi_mask=`/davinci/dvr/cfg get network wifi_mask`
        
            ifconfig ${devname} up ${wifi_ip}
            ifconfig ${devname} netmask ${wifi_mask}

		    case ${wifi_enc} in
		    "0")
		        # Disable (no enc)
		        /davinci/iwpriv ${devname} set NetworkType=Infra
	            /davinci/iwpriv ${devname} set AuthMode=OPEN
	            /davinci/iwpriv ${devname} set EncrypType=NONE
    		    /davinci/iwpriv ${devname} set SSID=${wifi_essid}
	    	    ;;
		    "1")
		        # WEP open
	            /davinci/iwpriv ${devname} set NetworkType=Infra
	            /davinci/iwpriv ${devname} set AuthMode=OPEN
	            /davinci/iwpriv ${devname} set EncrypType=WEP
	            /davinci/iwpriv ${devname} set Key1=${wifi_key}
	            /davinci/iwpriv ${devname} set DefaultKeyID=1
		        /davinci/iwpriv ${devname} set SSID=${wifi_essid}
		        ;;
		    "2")
		        # WEP shared
	            /davinci/iwpriv ${devname} set NetworkType=Infra
	            /davinci/iwpriv ${devname} set AuthMode=SHARED
	            /davinci/iwpriv ${devname} set EncrypType=WEP
	            /davinci/iwpriv ${devname} set Key1=$wifi_key
	            /davinci/iwpriv ${devname} set DefaultKeyID=1
		        /davinci/iwpriv ${devname} set SSID=$wifi_essid
		        ;;
		    "3")
  		        # WEP auto
	            /davinci/iwpriv ${devname} set NetworkType=Infra
	            /davinci/iwpriv ${devname} set AuthMode=WEPAUTO
	            /davinci/iwpriv ${devname} set EncrypType=WEP
	            /davinci/iwpriv ${devname} set Key1=$wifi_key
	            /davinci/iwpriv ${devname} set DefaultKeyID=1
		        /davinci/iwpriv ${devname} set SSID=$wifi_essid
		        ;;
		    "4")
		        # WPA Personal TKIP
	            /davinci/iwpriv ${devname} set NetworkType=Infra
		        /davinci/iwpriv ${devname} set AuthMode=WPAPSK
		        /davinci/iwpriv ${devname} set EncrypType=TKIP
		        /davinci/iwpriv ${devname} set SSID=$wifi_essid
		        /davinci/iwpriv ${devname} set WPAPSK=$wifi_key
		        /davinci/iwpriv ${devname} set SSID=$wifi_essid
		        ;;
		    "5")
		        # WPA Personal AES
	            /davinci/iwpriv ${devname} set NetworkType=Infra
	            /davinci/iwpriv ${devname} set AuthMode=WPAPSK
	            /davinci/iwpriv ${devname} set EncrypType=AES
		        /davinci/iwpriv ${devname} set SSID=$wifi_essid
	            /davinci/iwpriv ${devname} set WPAPSK=$wifi_key
		        /davinci/iwpriv ${devname} set SSID=$wifi_essid
		        ;;
		    "6")
		        # WPA2 Personal TKIP
	            /davinci/iwpriv ${devname} set NetworkType=Infra
	            /davinci/iwpriv ${devname} set AuthMode=WPA2PSK
	            /davinci/iwpriv ${devname} set EncrypType=TKIP
		        /davinci/iwpriv ${devname} set SSID=$wifi_essid
	            /davinci/iwpriv ${devname} set WPAPSK=$wifi_key
		        /davinci/iwpriv ${devname} set SSID=$wifi_essid
		        ;;
		    "7")
		        # WPA2 Personal AES
	            /davinci/iwpriv ${devname} set NetworkType=Infra
	            /davinci/iwpriv ${devname} set AuthMode=WPA2PSK
	            /davinci/iwpriv ${devname} set EncrypType=AES
		        /davinci/iwpriv ${devname} set SSID=$wifi_essid
	            /davinci/iwpriv ${devname} set WPAPSK=$wifi_key
		        /davinci/iwpriv ${devname} set SSID=$wifi_essid
		        ;;
		    *)
		        ;;
		    esac

            ifconfig ${devname} up ${wifi_ip}
            ifconfig ${devname} netmask ${wifi_mask}

        fi

        ;;

    "remove")
    
        if [ ${devclass} = "block" -a -r ${xmountdir}/mount_${devname} ]; then

            mountdir=`cat ${xmountdir}/mount_${devname}`
            dvrsvrdown=0
            dvrpid=0

            # suspend dvrsvr
            if [ -f ${dvrpidfile} -a -f ${dvrcurdisk} ]; then
                dvrdisk=`cat ${dvrcurdisk}`
                if [ ${dvrdisk} = ${mountdir} ] ; then
                    dvrpid=`cat ${dvrpidfile}`
                    kill -USR1 ${dvrpid}
                    for x in 1 2 3 4 5 6 7 8 9 10 ; do
                        if [ -f ${dvrcurdisk} ]; then
                            sleep 3
                        else
                            break
                        fi
                    done
                    dvrsvrdown=1
                fi
            fi

            for x in 1 2 3 4 5 6 7 8 ; do
                if [ -d ${mountdir} ] ; then
                   sync;
                   if umount ${mountdir} ; then
                      rm -r ${mountdir}
                   else
                      sleep 1
                   fi
                else
                   break
                fi ;
            done ;

            # restart dvrsvr
            if [ $dvrsvrdown = 1 ]; then
                kill -USR2 $dvrpid
            fi

            rm ${xmountdir}/mount_${devname}

        fi;
               
        
        ;;
esac 

# unlock hotplug
rm ${lockfile}
