#!/bin/sh

# Changes:
# 09/25/2009 Harrison
#   1. changes required for console=ttyS2

PATH=/bin:/davinci:/davinci/dvr

if [ -d /var/dvr ]; then
	exit 1
fi

mkdir /var/dvr
mkdir /var/dvr/disks

#clean some ram disk space. (hikvison files)
rm -r /opt/*

#telnet support
cp /davinci/dvr/passwd /etc

# set ip address
boardid=`cat /davinci/ID/BOARDID`
ifconfig eth0 192.168.247.${boardid}

# mount debugging disks
mount -t nfs 192.168.247.100:/home/dennis/nfsroot /mnt/nfs0 -o nolock

# see if I want to debug it
if [ -f /mnt/nfs0/eagletest/debugon ]; then
    exit ;
else
    umount /mnt/nfs0
fi

cd /davinci/dvr

# set up a new ip generated by host eagle32 board.
if ./slaveip ${boardid} hostid ; then 
    # check if firmware is up to date
    if [ -f firmwareid -a  `./nfile eaglehost 15160` = `cat firmwareid` ]; then
	echo Firmware verify ok!
    else
	# firmware not match
	echo Update slave board firmware...
	./nfile eaglehost 15161 > /home/slvfirmware
	chmod a+x /home/slvfirmware
	mkdir /home/slvfwupd
	cd /home/slvfwupd
	../slvfirmware
	cd ..
	rm -r /home/slvfwupd
	rm /home/slvfirmware
	echo Update slave board firmware finished.
	cd /davinci/dvr
    fi
fi

# firmware ready

cd /davinci
insmod /davinci/dsplinkk.ko ddr_start=0x83100080 ddr_size=0x00efff80

rm -f /dev/dsplink
mknod /dev/dsplink c `/bin/awk "\\$2==\"dsplink\" {print \\$1}" /proc/devices` 0

rm -f /dev/hikgpio
mknod /dev/hikgpio c `/bin/awk "\\$2==\"hikgpio\" {print \\$1}" /proc/devices` 0

check_rs232

workdir=/davinci/dvr
cd ${workdir}

mkdir /etc/dvr
cp ${workdir}/dvrip.conf /etc/dvr/dvr.conf

# start dvr server
./dvrsvr

# avoid problems relating to console=ttyS2
echo "#" > /etc/profile
echo "#" > /home/start.sh
