#!/bin/sh

# Changes:
# 09/25/2009 Harrison
#   1. changes required for console=ttyS2

PATH=/bin:/dav:/dav/dvr

if [ -d /var/dvr ]; then
	exit 1
fi

mkdir /var/dvr
mkdir /var/dvr/disks

#clean some ram disk space. (hikvison files)
rm -r /opt/*

#telnet support
cp /dav/dvr/passwd /etc

# set ip address
boardid=`cat /dav/ID/BOARDID`
ifconfig eth0 192.168.1.101

# mount debugging disks

# see if I want to debug it
#if [ -f /mnt/nfs0/eagletest/debugon ]; then
#    exit ;
#else
#    umount /mnt/nfs0
#fi

insmod /dav/jbd.ko
insmod /dav/mbcache.ko
insmod /dav/ext3.ko

cd /dav/dvr

# start io module
/dav/dvr/ioprocess < /dev/null > /dev/null 2> /dev/null &

# set up a new ip generated by host eagle32 board.
if ./slaveip ${boardid} hostid ; then 
    # check if firmware is up to date
    if [ -f firmwareid -a  `./nfile eaglehost 15160` = `cat firmwareid` ]; then
	echo Firmware verify ok!
    else
	# firmware not match
	echo Update slave board firmware...
	./nfile eaglehost 15161 > /home/slvfirmware
	chmod a+x /home/slvfirmware
	mkdir /home/slvfwupd
	cd /home/slvfwupd
	../slvfirmware
	cd ..
	rm -r /home/slvfwupd
	rm /home/slvfirmware
	echo Update slave board firmware finished.
	cd /dav/dvr
    fi
fi

# firmware ready

workdir=/dav/dvr
cd ${workdir}

mkdir /etc/dvr
cp ${workdir}/dvrip.conf /etc/dvr/dvr.conf

# start dvr server
./dvrsvr

# avoid problems relating to console=ttyS2
#echo "#" > /etc/profile
#echo "#" > /home/start.sh
