#!/bin/sh
# /etc/init.d/synctime: sync system time to RTC
# chkconfig: 2345 02 69

PATH=/sbin:/bin:/usr/bin

RETVAL=0

prog="setmodelname"


start(){
    echo -n "Starting $prog: "
	echo "."
	modelname=`fw_printenv | grep modelname | awk -F'=' '{ print $2 }'`
	

	sed -i "s/#modelname#/$modelname/g" /etc/conf.d/system.xml
	

}

stop(){
    echo -n "Stopping $prog: "
	echo "."
}

# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
    stop
    start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
