#!/bin/sh
echo Start update MDVR5104 firmware...
echo Kill processes...
if [ -f /var/dvr/dvrsvr.pid ]; then
  kill `cat /var/dvr/dvrsvr.pid` 
fi

if [ -f /var/dvr/glog.pid ]; then
  kill `cat /var/dvr/glog.pid`
fi

if [ -f /var/dvr/ioprocess.pid ]; then
   kill `cat /var/dvr/ioprocess.pid`
fi

for i in 1 2 3 4 5 6 7 8 9 10 ; do
  if [ -f /var/dvr/ioprocess.pid ]; then
    sleep 2
  else
    break;
  fi
done

sleep 1
./dvr/ioprocess &
sleep 1

# flashing panel leds
./dvr/panelled 07

for i in 1 2 3 4 5 6 7 8 9 10 ; do
  if [ -f /var/dvr/dvrsvr.pid ]; then
    sleep 2
  else
    break;
  fi
done

for i in 1 2 3 4 5 6 7 8 9 10 ; do
  if [ -f /var/dvr/glog.pid ]; then
    sleep 2
  else
    break;
  fi
done

# remove old files

# start copying files
echo Copying file to /davinci, please wait.
cp -f -a * /davinci
rm /davinci/sfxrun
sync

# stop panel led flashing
./dvr/panelled 0

echo Firmware update complete.
echo Remove any USB flash.
echo Turn off system power and turn on power again.

cd /davinci/dvr
./ioprocess -reboot 8


